spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:C:\Users\Kyu\Desktop\workspace\h2-2019-10-14\h2\db\test
    username: sa
    password: 1234